import { Player, Tournament, Club } from '@/types';

// Mock players for demo
export const mockPlayers: Player[] = [
    {
        id: '1',
        email: 'sarah@example.com',
        name: 'Sarah Chen',
        bio: 'Love doubles! Looking for a regular partner for weekend games. Been playing for 3 years.',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
        skillLevel: 6,
        playStyle: 'doubles',
        location: { lat: 52.4862, lng: -1.8904, city: 'Birmingham' },
        stats: {
            wins: 45,
            losses: 23,
            totalMatches: 68,
            winRate: 66,
            preferredDays: ['Saturday', 'Sunday'],
            averageRating: 4.5,
        },
        lookingFor: ['casual', 'competitive'],
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-02-01T14:30:00Z',
    },
    {
        id: '2',
        email: 'james@example.com',
        name: 'James Wilson',
        bio: 'Competitive singles player. Training for local tournaments. Let\'s rally! 🏸',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        skillLevel: 8,
        playStyle: 'singles',
        location: { lat: 52.4796, lng: -1.9026, city: 'Birmingham' },
        stats: {
            wins: 89,
            losses: 31,
            totalMatches: 120,
            winRate: 74,
            preferredDays: ['Monday', 'Wednesday', 'Friday'],
            averageRating: 4.8,
        },
        lookingFor: ['competitive'],
        createdAt: '2023-11-20T08:00:00Z',
        updatedAt: '2024-02-05T16:45:00Z',
    },
    {
        id: '3',
        email: 'priya@example.com',
        name: 'Priya Patel',
        bio: 'Beginner looking to improve! Patient partners welcome. Available most evenings.',
        avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
        skillLevel: 3,
        playStyle: 'both',
        location: { lat: 52.4751, lng: -1.8686, city: 'Birmingham' },
        stats: {
            wins: 12,
            losses: 28,
            totalMatches: 40,
            winRate: 30,
            preferredDays: ['Tuesday', 'Thursday'],
            averageRating: 4.2,
        },
        lookingFor: ['casual', 'coaching'],
        createdAt: '2024-02-01T12:00:00Z',
        updatedAt: '2024-02-06T09:15:00Z',
    },
    {
        id: '4',
        email: 'marcus@example.com',
        name: 'Marcus Thompson',
        bio: 'Ex-university team captain. Happy to coach beginners or play competitive matches!',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
        skillLevel: 9,
        playStyle: 'both',
        location: { lat: 52.4508, lng: -1.9305, city: 'Birmingham' },
        stats: {
            wins: 156,
            losses: 44,
            totalMatches: 200,
            winRate: 78,
            preferredDays: ['Saturday', 'Sunday', 'Wednesday'],
            averageRating: 4.9,
        },
        lookingFor: ['competitive', 'coaching'],
        createdAt: '2023-08-10T14:00:00Z',
        updatedAt: '2024-02-04T11:30:00Z',
    },
    {
        id: '5',
        email: 'emma@example.com',
        name: 'Emma Rodriguez',
        bio: 'Social player who loves the game! Always up for a friendly match and post-game drinks.',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
        skillLevel: 5,
        playStyle: 'doubles',
        location: { lat: 52.4922, lng: -1.8745, city: 'Birmingham' },
        stats: {
            wins: 34,
            losses: 36,
            totalMatches: 70,
            winRate: 49,
            preferredDays: ['Friday', 'Saturday'],
            averageRating: 4.6,
        },
        lookingFor: ['casual'],
        createdAt: '2024-01-05T16:00:00Z',
        updatedAt: '2024-02-02T13:20:00Z',
    },
    {
        id: '6',
        email: 'david@example.com',
        name: 'David Kim',
        bio: 'New to the area! Looking to join the local badminton scene. Intermediate player.',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
        skillLevel: 5,
        playStyle: 'singles',
        location: { lat: 52.4668, lng: -1.9123, city: 'Birmingham' },
        stats: {
            wins: 22,
            losses: 18,
            totalMatches: 40,
            winRate: 55,
            preferredDays: ['Monday', 'Thursday', 'Saturday'],
            averageRating: 4.3,
        },
        lookingFor: ['casual', 'competitive'],
        createdAt: '2024-01-28T09:00:00Z',
        updatedAt: '2024-02-06T10:00:00Z',
    },
    {
        id: '7',
        email: 'lisa@example.com',
        name: 'Lisa Chang',
        bio: 'Morning player! Love 7am sessions before work. Doubles preferred.',
        avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400',
        skillLevel: 7,
        playStyle: 'doubles',
        location: { lat: 52.4835, lng: -1.8567, city: 'Birmingham' },
        stats: {
            wins: 67,
            losses: 33,
            totalMatches: 100,
            winRate: 67,
            preferredDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
            averageRating: 4.7,
        },
        lookingFor: ['competitive'],
        createdAt: '2023-10-15T07:00:00Z',
        updatedAt: '2024-02-05T06:30:00Z',
    },
    {
        id: '8',
        email: 'alex@example.com',
        name: 'Alex Nguyen',
        bio: 'Just picked up badminton 6 months ago and I\'m hooked! Looking for patient practice partners.',
        avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400',
        skillLevel: 2,
        playStyle: 'both',
        location: { lat: 52.4589, lng: -1.8834, city: 'Birmingham' },
        stats: {
            wins: 5,
            losses: 15,
            totalMatches: 20,
            winRate: 25,
            preferredDays: ['Sunday'],
            averageRating: 4.0,
        },
        lookingFor: ['casual', 'coaching'],
        createdAt: '2024-02-03T11:00:00Z',
        updatedAt: '2024-02-06T15:45:00Z',
    },
];

// Mock tournaments
export const mockTournaments: Tournament[] = [
    {
        id: 't1',
        name: 'Birmingham Spring Open',
        description: 'Annual spring tournament open to all skill levels. Great prizes and atmosphere!',
        location: {
            lat: 52.4862,
            lng: -1.8904,
            venue: 'Aston University Sports Centre',
            address: 'Aston St, Birmingham B4 7ET',
        },
        date: '2026-03-15T09:00:00Z',
        endDate: '2026-03-15T18:00:00Z',
        format: 'singles',
        skillLevelMin: 1,
        skillLevelMax: 10,
        maxPlayers: 32,
        currentPlayers: ['1', '2', '4', '7'],
        entryFee: 15,
        prizes: ['Trophy', '£100 voucher', 'Free coaching session'],
        organizer: 'Birmingham Badminton Association',
        createdAt: '2024-01-10T10:00:00Z',
    },
    {
        id: 't2',
        name: 'Doubles Championship 2026',
        description: 'Competitive doubles tournament. Find a partner and compete!',
        location: {
            lat: 52.4751,
            lng: -1.8686,
            venue: 'National Indoor Arena',
            address: 'King Edwards Rd, Birmingham B1 2AA',
        },
        date: '2026-04-20T10:00:00Z',
        endDate: '2026-04-21T17:00:00Z',
        format: 'doubles',
        skillLevelMin: 5,
        skillLevelMax: 10,
        maxPlayers: 16,
        currentPlayers: ['2', '4'],
        entryFee: 25,
        prizes: ['Championship Trophy', '£250 cash', 'Pro racket set'],
        organizer: 'Midlands Badminton League',
        createdAt: '2024-01-20T14:00:00Z',
    },
    {
        id: 't3',
        name: 'Beginner Friendly Fun Tournament',
        description: 'No pressure, just fun! Perfect for those new to competitive play.',
        location: {
            lat: 52.4922,
            lng: -1.8745,
            venue: 'Selly Oak Leisure Centre',
            address: 'Bristol Rd, Birmingham B29 6SL',
        },
        date: '2026-02-28T13:00:00Z',
        endDate: '2026-02-28T17:00:00Z',
        format: 'mixed',
        skillLevelMin: 1,
        skillLevelMax: 4,
        maxPlayers: 24,
        currentPlayers: ['3', '5', '8'],
        entryFee: 10,
        prizes: ['Medals', 'Shuttlecock pack'],
        organizer: 'Selly Oak Badminton Club',
        createdAt: '2024-02-01T09:00:00Z',
    },
    {
        id: 't4',
        name: 'University League Finals',
        description: 'The grand finale of the inter-university badminton league.',
        location: {
            lat: 52.4508,
            lng: -1.9305,
            venue: 'University of Birmingham Sport Centre',
            address: 'Edgbaston, Birmingham B15 2TT',
        },
        date: '2026-05-10T11:00:00Z',
        endDate: '2026-05-10T19:00:00Z',
        format: 'singles',
        skillLevelMin: 6,
        skillLevelMax: 10,
        maxPlayers: 16,
        currentPlayers: [],
        entryFee: 0,
        prizes: ['University Trophy', 'Champion Title'],
        organizer: 'BUCS',
        createdAt: '2024-01-25T11:00:00Z',
    },
];

// Mock clubs
export const mockClubs: Club[] = [
    {
        id: 'c1',
        name: 'Birmingham Badminton Club',
        description: 'The largest and oldest badminton club in Birmingham. Weekly sessions, coaching, and social events.',
        avatarUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400',
        location: {
            lat: 52.4862,
            lng: -1.8904,
            address: 'Aston University Sports Centre, Birmingham B4 7ET',
        },
        memberCount: 156,
        members: ['1', '2', '4', '7'],
        activityLevel: 'high',
        meetingDays: ['Tuesday', 'Thursday', 'Saturday'],
        skillLevelRange: [1, 10],
        isOpen: true,
        createdAt: '2020-01-15T10:00:00Z',
    },
    {
        id: 'c2',
        name: 'Aston Shuttlers',
        description: 'Aston University students and alumni. Casual and competitive play welcome!',
        avatarUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400',
        location: {
            lat: 52.4870,
            lng: -1.8895,
            address: 'Aston University, Aston St, Birmingham B4 7ET',
        },
        memberCount: 89,
        members: ['current', '3', '5', '6', '8'],
        activityLevel: 'high',
        meetingDays: ['Monday', 'Wednesday', 'Friday'],
        skillLevelRange: [1, 8],
        isOpen: true,
        createdBy: 'current', // Created by the demo user
        createdAt: '2021-09-01T10:00:00Z',
    },
    {
        id: 'c3',
        name: 'Elite Smashers',
        description: 'Competitive club for advanced players. Regular training and tournament preparation.',
        avatarUrl: 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=400',
        location: {
            lat: 52.4668,
            lng: -1.9123,
            address: 'Edgbaston Priory Club, Birmingham B15 3TB',
        },
        memberCount: 34,
        members: ['2', '4'],
        activityLevel: 'high',
        meetingDays: ['Monday', 'Wednesday', 'Saturday', 'Sunday'],
        skillLevelRange: [7, 10],
        isOpen: false,
        createdAt: '2019-06-10T10:00:00Z',
    },
    {
        id: 'c4',
        name: 'Weekend Warriors',
        description: 'Casual weekend club for those who just want to have fun. All levels welcome!',
        avatarUrl: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400',
        location: {
            lat: 52.4589,
            lng: -1.8834,
            address: 'Harborne Leisure Centre, Birmingham B17 9LS',
        },
        memberCount: 67,
        members: ['1', '3', '5', '6', '8'],
        activityLevel: 'medium',
        meetingDays: ['Saturday', 'Sunday'],
        skillLevelRange: [1, 6],
        isOpen: true,
        createdAt: '2022-03-20T10:00:00Z',
    },
];

// Current user for demo
export const mockCurrentUser: Player = {
    id: 'current',
    email: 'demo@badmintonconnect.com',
    name: 'Demo User',
    bio: 'Hackathon demo account! Looking to connect with the badminton community.',
    avatarUrl: 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=400',
    skillLevel: 5,
    playStyle: 'both',
    location: { lat: 52.4862, lng: -1.8904, city: 'Birmingham' },
    stats: {
        wins: 25,
        losses: 20,
        totalMatches: 45,
        winRate: 56,
        preferredDays: ['Wednesday', 'Saturday', 'Sunday'],
        averageRating: 4.4,
    },
    lookingFor: ['casual', 'competitive'],
    createdAt: '2024-02-07T10:00:00Z',
    updatedAt: '2024-02-07T10:00:00Z',
};

// Courts/venues for map
export const mockCourts = [
    {
        id: 'court1',
        name: 'Aston University Sports Centre',
        lat: 52.4862,
        lng: -1.8904,
        courts: 6,
        hourlyRate: 12,
    },
    {
        id: 'court2',
        name: 'National Indoor Arena',
        lat: 52.4751,
        lng: -1.8686,
        courts: 8,
        hourlyRate: 15,
    },
    {
        id: 'court3',
        name: 'Selly Oak Leisure Centre',
        lat: 52.4922,
        lng: -1.8745,
        courts: 4,
        hourlyRate: 10,
    },
    {
        id: 'court4',
        name: 'University of Birmingham Sport Centre',
        lat: 52.4508,
        lng: -1.9305,
        courts: 10,
        hourlyRate: 8,
    },
];

// Mock Organised Tournaments (by current user as organiser)
export const mockOrganisedTournaments = [
    {
        id: 'mt1',
        name: 'Birmingham Spring Open 2026',
        description: 'Annual spring tournament open to all skill levels. Great prizes and atmosphere!',
        date: '2026-03-15',
        endDate: '2026-03-16',
        location: {
            venue: 'Aston University Sports Centre',
            address: 'Aston St, Birmingham B4 7ET',
        },
        status: 'pending' as const,
        scale: 'Open Entries (Local)',
        format: 'singles' as const,
        maxAthletes: 32,
        athletesRegistered: 12,
        hiringPersonnel: true,
        positions: [
            { role: 'Line Judge', wage: 12, slots: 8, filled: 3 },
            { role: 'Umpire', wage: 18, slots: 4, filled: 1 },
            { role: 'Scorer', wage: 10, slots: 6, filled: 2 },
        ],
        applicationsCount: 8,
        createdAt: '2026-01-15T10:00:00Z',
        organiserId: 'current-user',
    },
    {
        id: 'mt2',
        name: 'Summer Smash Championship',
        description: 'Competitive doubles tournament for intermediate to advanced players.',
        date: '2026-06-20',
        endDate: '2026-06-21',
        location: {
            venue: 'Birmingham Sports Hub',
            address: 'Park Street, Birmingham B5 5JR',
        },
        status: 'draft' as const,
        scale: 'County Level',
        format: 'doubles' as const,
        maxAthletes: 64,
        athletesRegistered: 0,
        hiringPersonnel: true,
        positions: [
            { role: 'Line Judge', wage: 15, slots: 12, filled: 0 },
            { role: 'Umpire', wage: 20, slots: 6, filled: 0 },
        ],
        applicationsCount: 0,
        createdAt: '2026-02-01T14:00:00Z',
        organiserId: 'current-user',
    },
    {
        id: 'mt3',
        name: 'Autumn Mixed Doubles',
        description: 'Fun mixed doubles event for all levels.',
        date: '2026-09-10',
        location: {
            venue: 'Perry Barr Leisure Centre',
            address: 'Aldridge Road, Birmingham B42 2ET',
        },
        status: 'pending' as const,
        scale: 'Open Entries (Local)',
        format: 'mixed' as const,
        maxAthletes: 24,
        athletesRegistered: 8,
        hiringPersonnel: false,
        positions: [],
        applicationsCount: 0,
        createdAt: '2026-02-05T09:00:00Z',
        organiserId: 'current-user',
    },
];

// Mock Staff Applications
export const mockStaffApplications = [
    {
        id: 'app1',
        jobId: 'job1',
        tournamentId: 'mt1',
        position: 'Line Judge',
        wage: 12,
        applicantId: 'applicant1',
        fullName: 'John Smith',
        email: 'john.smith@email.com',
        phone: '07123456789',
        photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
        experiences: [
            {
                id: 'exp1',
                tournamentName: 'City Championship 2025',
                role: 'Line Judge',
                dateFrom: '2025-03-15',
                dateTo: '2025-03-16',
                description: 'Served as line judge for 20+ matches across 2 days',
            },
            {
                id: 'exp2',
                tournamentName: 'Regional Open 2024',
                role: 'Scorer',
                dateFrom: '2024-09-10',
                dateTo: '2024-09-10',
                description: 'Managed scoring for singles and doubles matches',
            },
        ],
        cvUrl: '/uploads/john_smith_cv.pdf',
        coverLetter: 'I am passionate about badminton and have been involved in the sport for over 10 years. I have experience as a line judge and scorer at various local tournaments. I am reliable, punctual, and have excellent attention to detail.',
        availability: ['March 15, 2026', 'March 16, 2026'],
        status: 'pending' as const,
        appliedAt: '2026-02-05T10:30:00Z',
    },
    {
        id: 'app2',
        jobId: 'job2',
        tournamentId: 'mt1',
        position: 'Umpire',
        wage: 18,
        applicantId: 'applicant2',
        fullName: 'Sarah Johnson',
        email: 'sarah.j@email.com',
        phone: '07987654321',
        photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
        experiences: [
            {
                id: 'exp3',
                tournamentName: 'National Junior Championships 2024',
                role: 'Umpire',
                dateFrom: '2024-07-20',
                dateTo: '2024-07-23',
                description: 'BWF certified umpire for junior national event',
            },
            {
                id: 'exp4',
                tournamentName: 'County League Finals 2025',
                role: 'Umpire',
                dateFrom: '2025-05-15',
                dateTo: '2025-05-15',
                description: 'Chief umpire for county finals',
            },
            {
                id: 'exp5',
                tournamentName: 'Birmingham Open 2024',
                role: 'Line Judge',
                dateFrom: '2024-04-10',
                dateTo: '2024-04-11',
                description: 'Line judge for open tournament',
            },
        ],
        cvUrl: '/uploads/sarah_johnson_cv.pdf',
        coverLetter: 'As a BWF certified umpire with 5 years of experience, I would love to be part of your tournament. I have officiated at national and county level events and pride myself on fair and consistent officiating.',
        availability: ['March 15, 2026', 'March 16, 2026'],
        status: 'pending' as const,
        appliedAt: '2026-02-04T14:15:00Z',
    },
    {
        id: 'app3',
        jobId: 'job1',
        tournamentId: 'mt1',
        position: 'Line Judge',
        wage: 12,
        applicantId: 'applicant3',
        fullName: 'Michael Chen',
        email: 'mchen@email.com',
        phone: '07555123456',
        photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        experiences: [
            {
                id: 'exp6',
                tournamentName: 'University Championships 2025',
                role: 'Line Judge',
                dateFrom: '2025-02-20',
                dateTo: '2025-02-21',
                description: 'Volunteered as line judge',
            },
        ],
        cvUrl: '/uploads/michael_chen_cv.pdf',
        coverLetter: 'I am a university student looking to gain more experience in tournament officiating. I have basic training and am eager to learn from experienced officials.',
        availability: ['March 15, 2026'],
        status: 'under_review' as const,
        appliedAt: '2026-02-06T09:00:00Z',
        reviewedAt: '2026-02-06T15:00:00Z',
        notes: 'Limited experience but enthusiastic. Consider for backup.',
    },
    {
        id: 'app4',
        jobId: 'job3',
        tournamentId: 'mt1',
        position: 'Scorer',
        wage: 10,
        applicantId: 'applicant4',
        fullName: 'Emily Watson',
        email: 'emily.w@email.com',
        phone: '07444567890',
        photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
        experiences: [],
        cvUrl: '/uploads/emily_watson_cv.pdf',
        coverLetter: 'Although I am new to tournament work, I am highly organised and quick to learn. I have played badminton for 5 years and understand the scoring system well.',
        availability: ['March 15, 2026', 'March 16, 2026'],
        status: 'accepted' as const,
        appliedAt: '2026-02-03T11:00:00Z',
        reviewedAt: '2026-02-05T10:00:00Z',
        notes: 'No experience but good attitude. Paired with experienced scorer.',
    },
    {
        id: 'app5',
        jobId: 'job1',
        tournamentId: 'mt1',
        position: 'Line Judge',
        wage: 12,
        applicantId: 'applicant5',
        fullName: 'David Park',
        email: 'dpark@email.com',
        phone: '07666789012',
        photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
        experiences: [
            {
                id: 'exp7',
                tournamentName: 'All England Junior 2023',
                role: 'Line Judge',
                dateFrom: '2023-03-01',
                dateTo: '2023-03-05',
                description: 'Line judge at premier junior event',
            },
            {
                id: 'exp8',
                tournamentName: 'European Junior Championships 2024',
                role: 'Line Judge',
                dateFrom: '2024-04-15',
                dateTo: '2024-04-20',
                description: 'International line judge experience',
            },
        ],
        cvUrl: '/uploads/david_park_cv.pdf',
        coverLetter: 'I have international and national experience as a line judge. I am committed to maintaining high standards of officiating.',
        availability: ['March 15, 2026', 'March 16, 2026'],
        status: 'accepted' as const,
        appliedAt: '2026-02-02T16:30:00Z',
        reviewedAt: '2026-02-04T09:00:00Z',
        notes: 'Excellent experience. Confirmed.',
    },
    {
        id: 'app6',
        jobId: 'job2',
        tournamentId: 'mt1',
        position: 'Umpire',
        wage: 18,
        applicantId: 'applicant6',
        fullName: 'Lisa Thompson',
        email: 'lisa.t@email.com',
        phone: '07777890123',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
        experiences: [
            {
                id: 'exp9',
                tournamentName: 'County Championships 2025',
                role: 'Umpire',
                dateFrom: '2025-06-10',
                dateTo: '2025-06-12',
                description: 'Lead umpire for county event',
            },
        ],
        cvUrl: '/uploads/lisa_thompson_cv.pdf',
        coverLetter: 'I have been umpiring for 3 years and hold a level 2 certification. I enjoy working at local tournaments and helping them run smoothly.',
        availability: ['March 16, 2026'],
        status: 'rejected' as const,
        appliedAt: '2026-02-01T13:00:00Z',
        reviewedAt: '2026-02-03T14:00:00Z',
        notes: 'Only available one day - need full availability for umpire role.',
    },
    {
        id: 'app7',
        jobId: 'job3',
        tournamentId: 'mt1',
        position: 'Scorer',
        wage: 10,
        applicantId: 'applicant7',
        fullName: 'Tom Richards',
        email: 'tom.r@email.com',
        phone: '07888901234',
        photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400',
        experiences: [
            {
                id: 'exp10',
                tournamentName: 'Local Club Championship 2025',
                role: 'Scorer',
                dateFrom: '2025-11-20',
                dateTo: '2025-11-20',
                description: 'Scorer for club internal tournament',
            },
        ],
        cvUrl: '/uploads/tom_richards_cv.pdf',
        coverLetter: 'I am available for both days and have experience with electronic scoring systems.',
        availability: ['March 15, 2026', 'March 16, 2026'],
        status: 'pending' as const,
        appliedAt: '2026-02-06T10:00:00Z',
    },
    {
        id: 'app8',
        jobId: 'job1',
        tournamentId: 'mt1',
        position: 'Line Judge',
        wage: 12,
        applicantId: 'applicant8',
        fullName: 'Anna Kowalski',
        email: 'anna.k@email.com',
        phone: '07999012345',
        photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400',
        experiences: [
            {
                id: 'exp11',
                tournamentName: 'Polish Open 2024',
                role: 'Line Judge',
                dateFrom: '2024-08-10',
                dateTo: '2024-08-13',
                description: 'International tournament experience',
            },
        ],
        cvUrl: '/uploads/anna_kowalski_cv.pdf',
        coverLetter: 'Recently moved to Birmingham. Have international experience and am looking for local opportunities.',
        availability: ['March 15, 2026', 'March 16, 2026'],
        status: 'pending' as const,
        appliedAt: '2026-02-06T14:00:00Z',
    },
];

// Mock Athlete Registrations
export const mockAthleteRegistrations = [
    {
        id: 'reg1',
        tournamentId: 'mt1',
        playerId: '4',
        player: mockPlayers.find(p => p.id === '4'),
        discipline: ["Men's Singles"],
        category: 'Senior (21+)',
        gender: 'Male',
        skillLevel: 9 as const,
        registeredAt: '2026-02-05T14:00:00Z',
        status: 'confirmed' as const,
    },
    {
        id: 'reg2',
        tournamentId: 'mt1',
        playerId: '2',
        player: mockPlayers.find(p => p.id === '2'),
        discipline: ["Men's Singles"],
        category: 'Senior (21+)',
        gender: 'Male',
        skillLevel: 8 as const,
        registeredAt: '2026-02-04T10:00:00Z',
        status: 'confirmed' as const,
    },
    {
        id: 'reg3',
        tournamentId: 'mt1',
        playerId: '1',
        player: mockPlayers.find(p => p.id === '1'),
        discipline: ["Women's Singles"],
        category: 'Senior (21+)',
        gender: 'Female',
        skillLevel: 6 as const,
        registeredAt: '2026-02-03T16:00:00Z',
        status: 'confirmed' as const,
    },
    {
        id: 'reg4',
        tournamentId: 'mt1',
        playerId: '5',
        player: mockPlayers.find(p => p.id === '5'),
        discipline: ["Women's Singles"],
        category: 'Senior (21+)',
        gender: 'Female',
        skillLevel: 5 as const,
        registeredAt: '2026-02-02T11:00:00Z',
        status: 'registered' as const,
    },
    {
        id: 'reg5',
        tournamentId: 'mt1',
        playerId: '3',
        player: mockPlayers.find(p => p.id === '3'),
        discipline: ["Women's Singles"],
        category: 'Senior (21+)',
        gender: 'Female',
        skillLevel: 3 as const,
        registeredAt: '2026-02-06T09:00:00Z',
        status: 'registered' as const,
    },
    {
        id: 'reg6',
        tournamentId: 'mt1',
        playerId: '6',
        player: mockPlayers.find(p => p.id === '6'),
        discipline: ["Men's Singles"],
        category: 'Senior (21+)',
        gender: 'Male',
        skillLevel: 5 as const,
        registeredAt: '2026-02-01T13:00:00Z',
        status: 'confirmed' as const,
    },
    {
        id: 'reg7',
        tournamentId: 'mt1',
        playerId: '7',
        player: mockPlayers.find(p => p.id === '7'),
        discipline: ["Women's Singles"],
        category: 'Senior (21+)',
        gender: 'Female',
        skillLevel: 7 as const,
        registeredAt: '2026-01-30T15:00:00Z',
        status: 'confirmed' as const,
    },
    {
        id: 'reg8',
        tournamentId: 'mt3',
        playerId: '1',
        player: mockPlayers.find(p => p.id === '1'),
        discipline: ['Mixed Doubles'],
        category: 'Senior (21+)',
        gender: 'Female',
        skillLevel: 6 as const,
        registeredAt: '2026-02-05T10:00:00Z',
        status: 'registered' as const,
    },
];

// Mock Tournament Jobs (available for workers to apply)
export const mockTournamentJobs = [
    {
        id: 'job1',
        tournamentId: 'mt1',
        tournamentName: 'Birmingham Spring Open 2026',
        role: 'Line Judge',
        description: 'Responsible for making line calls during matches. Must have good eyesight and be able to stand for extended periods.',
        wage: 12,
        slots: 8,
        filled: 3,
        requirements: ['Good eyesight', 'Ability to stand for 4+ hours', 'Basic badminton knowledge'],
        dates: ['March 15, 2026', 'March 16, 2026'],
        location: 'Aston University Sports Centre',
        applicationDeadline: '2026-03-01',
    },
    {
        id: 'job2',
        tournamentId: 'mt1',
        tournamentName: 'Birmingham Spring Open 2026',
        role: 'Umpire',
        description: 'Control matches, make decisions on service faults, and manage player conduct. BWF certification preferred.',
        wage: 18,
        slots: 4,
        filled: 1,
        requirements: ['BWF certification preferred', 'Previous umpiring experience', 'Excellent communication'],
        dates: ['March 15, 2026', 'March 16, 2026'],
        location: 'Aston University Sports Centre',
        applicationDeadline: '2026-03-01',
    },
    {
        id: 'job3',
        tournamentId: 'mt1',
        tournamentName: 'Birmingham Spring Open 2026',
        role: 'Scorer',
        description: 'Manage electronic scoring systems and update live scores. Training provided.',
        wage: 10,
        slots: 6,
        filled: 2,
        requirements: ['Basic computer skills', 'Attention to detail', 'Reliability'],
        dates: ['March 15, 2026', 'March 16, 2026'],
        location: 'Aston University Sports Centre',
        applicationDeadline: '2026-03-01',
    },
    {
        id: 'job4',
        tournamentId: 'mt2',
        tournamentName: 'Summer Smash Championship',
        role: 'Line Judge',
        description: 'Line judging for competitive doubles matches at county level event.',
        wage: 15,
        slots: 12,
        filled: 0,
        requirements: ['Previous experience required', 'County level or above'],
        dates: ['June 20, 2026', 'June 21, 2026'],
        location: 'Birmingham Sports Hub',
        applicationDeadline: '2026-06-01',
    },
    {
        id: 'job5',
        tournamentId: 'mt2',
        tournamentName: 'Summer Smash Championship',
        role: 'Umpire',
        description: 'Chief umpire and match umpires needed for county level doubles event.',
        wage: 20,
        slots: 6,
        filled: 0,
        requirements: ['BWF certified', 'County level experience minimum'],
        dates: ['June 20, 2026', 'June 21, 2026'],
        location: 'Birmingham Sports Hub',
        applicationDeadline: '2026-06-01',
    },
];

// Mock My Applications (for current user as worker)
type ApplicationStatus = 'pending' | 'under_review' | 'accepted' | 'rejected';

export const mockMyApplications: Array<{
    id: string;
    jobId: string;
    tournamentId: string;
    tournamentName: string;
    position: string;
    wage: number;
    location: string;
    dates: string[];
    status: ApplicationStatus;
    appliedAt: string;
}> = [
    {
        id: 'myapp1',
        jobId: 'job4',
        tournamentId: 'mt2',
        tournamentName: 'Summer Smash Championship',
        position: 'Line Judge',
        wage: 15,
        location: 'Birmingham Sports Hub',
        dates: ['June 20, 2026', 'June 21, 2026'],
        status: 'pending' as const,
        appliedAt: '2026-02-06T11:00:00Z',
    },
    {
        id: 'myapp2',
        jobId: 'job1',
        tournamentId: 'mt1',
        tournamentName: 'Birmingham Spring Open 2026',
        position: 'Line Judge',
        wage: 12,
        location: 'Aston University Sports Centre',
        dates: ['March 15, 2026', 'March 16, 2026'],
        status: 'accepted' as const,
        appliedAt: '2026-01-20T14:00:00Z',
    },
    {
        id: 'myapp3',
        jobId: 'job5',
        tournamentId: 'mt2',
        tournamentName: 'Summer Smash Championship',
        position: 'Umpire',
        wage: 20,
        location: 'Birmingham Sports Hub',
        dates: ['June 20, 2026', 'June 21, 2026'],
        status: 'under_review' as const,
        appliedAt: '2026-02-04T09:00:00Z',
    },
];

// Mock Partner Swipes (for swiping feature)
export const mockPartnerSwipes = [
    { id: 'swipe1', swiperId: 'current-user', swipedId: '1', direction: 'like' as const, createdAt: '2026-02-06T10:00:00Z' },
    { id: 'swipe2', swiperId: '1', swipedId: 'current-user', direction: 'like' as const, createdAt: '2026-02-06T09:00:00Z' },
];

// Mock Partner Matches
export const mockPartnerMatches = [
    {
        id: 'match1',
        player1Id: 'current-user',
        player2Id: '1',
        player1: mockCurrentUser,
        player2: mockPlayers.find(p => p.id === '1'),
        matchedAt: '2026-02-06T10:00:00Z',
        compatibility: 85,
    },
];

// Mock Booked Sessions (for scheduling & fare splitting)
export const mockBookedSessions = [
    {
        id: 'session1',
        date: '2026-02-10',
        time: '18:00',
        duration: 2,
        venue: {
            id: '1',
            name: 'Aston University Sports Centre',
            pricePerHour: 12,
        },
        participants: [
            { id: 'current-user', name: 'You', avatarUrl: '', share: 8, paid: true },
            { id: '1', name: 'Alex Chen', avatarUrl: 'https://i.pravatar.cc/150?img=11', share: 8, paid: true },
            { id: '2', name: 'Sarah Williams', avatarUrl: 'https://i.pravatar.cc/150?img=5', share: 8, paid: false },
        ],
        totalCost: 24,
        splitMode: 'equal' as const,
        status: 'upcoming' as const,
        createdAt: '2026-02-05T14:00:00Z',
        createdBy: 'current-user',
    },
    {
        id: 'session2',
        date: '2026-02-08',
        time: '10:00',
        duration: 1.5,
        venue: {
            id: '3',
            name: 'Nechells Community Centre',
            pricePerHour: 8,
        },
        participants: [
            { id: 'current-user', name: 'You', avatarUrl: '', share: 6, paid: true },
            { id: '3', name: 'Mike Johnson', avatarUrl: 'https://i.pravatar.cc/150?img=12', share: 6, paid: true },
        ],
        totalCost: 12,
        splitMode: 'equal' as const,
        status: 'completed' as const,
        createdAt: '2026-02-03T09:00:00Z',
        createdBy: 'current-user',
    },
    {
        id: 'session3',
        date: '2026-02-15',
        time: '14:00',
        duration: 2,
        venue: {
            id: '2',
            name: 'Birmingham Sports Hub',
            pricePerHour: 15,
        },
        participants: [
            { id: 'current-user', name: 'You', avatarUrl: '', share: 12, paid: true },
            { id: '4', name: 'Emma Davis', avatarUrl: 'https://i.pravatar.cc/150?img=9', share: 10, paid: false },
            { id: '5', name: 'James Wilson', avatarUrl: 'https://i.pravatar.cc/150?img=7', share: 8, paid: false },
        ],
        totalCost: 30,
        splitMode: 'custom' as const,
        status: 'pending' as const,
        createdAt: '2026-02-07T11:00:00Z',
        createdBy: 'current-user',
    },
    {
        id: 'session4',
        date: '2026-02-12',
        time: '19:00',
        duration: 1,
        venue: {
            id: '4',
            name: 'Perry Barr Leisure Centre',
            pricePerHour: 10,
        },
        participants: [
            { id: 'current-user', name: 'You', avatarUrl: '', share: 5, paid: false },
            { id: '6', name: 'Lisa Thompson', avatarUrl: 'https://i.pravatar.cc/150?img=23', share: 5, paid: false },
        ],
        totalCost: 10,
        splitMode: 'equal' as const,
        status: 'upcoming' as const,
        createdAt: '2026-02-07T16:00:00Z',
        createdBy: 'current-user',
    },
    {
        id: 'session5',
        date: '2026-02-20',
        time: '16:00',
        duration: 2.5,
        venue: {
            id: '2',
            name: 'Birmingham Sports Hub',
            pricePerHour: 15,
        },
        participants: [
            { id: 'current-user', name: 'You', avatarUrl: '', share: 9.375, paid: false },
            { id: '1', name: 'Alex Chen', avatarUrl: 'https://i.pravatar.cc/150?img=11', share: 9.375, paid: false },
            { id: '3', name: 'Mike Johnson', avatarUrl: 'https://i.pravatar.cc/150?img=12', share: 9.375, paid: false },
            { id: '7', name: 'Sophie Brown', avatarUrl: 'https://i.pravatar.cc/150?img=32', share: 9.375, paid: false },
        ],
        totalCost: 37.5,
        splitMode: 'equal' as const,
        status: 'pending' as const,
        createdAt: '2026-02-07T18:00:00Z',
        createdBy: 'current-user',
    },
];

// Mock Venues (for scheduling)
export const mockVenues = [
    { id: '1', name: 'Aston University Sports Centre', pricePerHour: 12, address: 'Aston Triangle, Birmingham B4 7ET', courts: 4 },
    { id: '2', name: 'Birmingham Sports Hub', pricePerHour: 15, address: 'Walsall Road, Birmingham B42 1TR', courts: 6 },
    { id: '3', name: 'Nechells Community Centre', pricePerHour: 8, address: 'Nechells Park Road, Birmingham B7 5PR', courts: 2 },
    { id: '4', name: 'Perry Barr Leisure Centre', pricePerHour: 10, address: 'Aldridge Road, Birmingham B42 2ET', courts: 3 },
    { id: '5', name: 'Sparkhill Pool & Fitness', pricePerHour: 9, address: 'Stratford Road, Birmingham B11 4EA', courts: 2 },
];
