import { Player, Tournament, Club } from '@/types';

// Mock players for demo
export const mockPlayers: Player[] = [
    {
        id: '1',
        email: 'sarah@example.com',
        name: 'Sarah Chen',
        bio: 'Love doubles! Looking for a regular partner for weekend games. Been playing for 3 years.',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
        skillLevel: 6,
        playStyle: 'doubles',
        location: { lat: 52.4862, lng: -1.8904, city: 'Birmingham' },
        stats: {
            wins: 45,
            losses: 23,
            totalMatches: 68,
            winRate: 66,
            preferredDays: ['Saturday', 'Sunday'],
            averageRating: 4.5,
        },
        lookingFor: ['casual', 'competitive'],
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-02-01T14:30:00Z',
    },
    {
        id: '2',
        email: 'james@example.com',
        name: 'James Wilson',
        bio: 'Competitive singles player. Training for local tournaments. Let\'s rally! 🏸',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        skillLevel: 8,
        playStyle: 'singles',
        location: { lat: 52.4796, lng: -1.9026, city: 'Birmingham' },
        stats: {
            wins: 89,
            losses: 31,
            totalMatches: 120,
            winRate: 74,
            preferredDays: ['Monday', 'Wednesday', 'Friday'],
            averageRating: 4.8,
        },
        lookingFor: ['competitive'],
        createdAt: '2023-11-20T08:00:00Z',
        updatedAt: '2024-02-05T16:45:00Z',
    },
    {
        id: '3',
        email: 'priya@example.com',
        name: 'Priya Patel',
        bio: 'Beginner looking to improve! Patient partners welcome. Available most evenings.',
        avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
        skillLevel: 3,
        playStyle: 'both',
        location: { lat: 52.4751, lng: -1.8686, city: 'Birmingham' },
        stats: {
            wins: 12,
            losses: 28,
            totalMatches: 40,
            winRate: 30,
            preferredDays: ['Tuesday', 'Thursday'],
            averageRating: 4.2,
        },
        lookingFor: ['casual', 'coaching'],
        createdAt: '2024-02-01T12:00:00Z',
        updatedAt: '2024-02-06T09:15:00Z',
    },
    {
        id: '4',
        email: 'marcus@example.com',
        name: 'Marcus Thompson',
        bio: 'Ex-university team captain. Happy to coach beginners or play competitive matches!',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
        skillLevel: 9,
        playStyle: 'both',
        location: { lat: 52.4508, lng: -1.9305, city: 'Birmingham' },
        stats: {
            wins: 156,
            losses: 44,
            totalMatches: 200,
            winRate: 78,
            preferredDays: ['Saturday', 'Sunday', 'Wednesday'],
            averageRating: 4.9,
        },
        lookingFor: ['competitive', 'coaching'],
        createdAt: '2023-08-10T14:00:00Z',
        updatedAt: '2024-02-04T11:30:00Z',
    },
    {
        id: '5',
        email: 'emma@example.com',
        name: 'Emma Rodriguez',
        bio: 'Social player who loves the game! Always up for a friendly match and post-game drinks.',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
        skillLevel: 5,
        playStyle: 'doubles',
        location: { lat: 52.4922, lng: -1.8745, city: 'Birmingham' },
        stats: {
            wins: 34,
            losses: 36,
            totalMatches: 70,
            winRate: 49,
            preferredDays: ['Friday', 'Saturday'],
            averageRating: 4.6,
        },
        lookingFor: ['casual'],
        createdAt: '2024-01-05T16:00:00Z',
        updatedAt: '2024-02-02T13:20:00Z',
    },
    {
        id: '6',
        email: 'david@example.com',
        name: 'David Kim',
        bio: 'New to the area! Looking to join the local badminton scene. Intermediate player.',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
        skillLevel: 5,
        playStyle: 'singles',
        location: { lat: 52.4668, lng: -1.9123, city: 'Birmingham' },
        stats: {
            wins: 22,
            losses: 18,
            totalMatches: 40,
            winRate: 55,
            preferredDays: ['Monday', 'Thursday', 'Saturday'],
            averageRating: 4.3,
        },
        lookingFor: ['casual', 'competitive'],
        createdAt: '2024-01-28T09:00:00Z',
        updatedAt: '2024-02-06T10:00:00Z',
    },
    {
        id: '7',
        email: 'lisa@example.com',
        name: 'Lisa Chang',
        bio: 'Morning player! Love 7am sessions before work. Doubles preferred.',
        avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400',
        skillLevel: 7,
        playStyle: 'doubles',
        location: { lat: 52.4835, lng: -1.8567, city: 'Birmingham' },
        stats: {
            wins: 67,
            losses: 33,
            totalMatches: 100,
            winRate: 67,
            preferredDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
            averageRating: 4.7,
        },
        lookingFor: ['competitive'],
        createdAt: '2023-10-15T07:00:00Z',
        updatedAt: '2024-02-05T06:30:00Z',
    },
    {
        id: '8',
        email: 'alex@example.com',
        name: 'Alex Nguyen',
        bio: 'Just picked up badminton 6 months ago and I\'m hooked! Looking for patient practice partners.',
        avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400',
        skillLevel: 2,
        playStyle: 'both',
        location: { lat: 52.4589, lng: -1.8834, city: 'Birmingham' },
        stats: {
            wins: 5,
            losses: 15,
            totalMatches: 20,
            winRate: 25,
            preferredDays: ['Sunday'],
            averageRating: 4.0,
        },
        lookingFor: ['casual', 'coaching'],
        createdAt: '2024-02-03T11:00:00Z',
        updatedAt: '2024-02-06T15:45:00Z',
    },
];

// Mock tournaments
export const mockTournaments: Tournament[] = [
    {
        id: 't1',
        name: 'Birmingham Spring Open',
        description: 'Annual spring tournament open to all skill levels. Great prizes and atmosphere!',
        location: {
            lat: 52.4862,
            lng: -1.8904,
            venue: 'Aston University Sports Centre',
            address: 'Aston St, Birmingham B4 7ET',
        },
        date: '2026-03-15T09:00:00Z',
        endDate: '2026-03-15T18:00:00Z',
        format: 'singles',
        skillLevelMin: 1,
        skillLevelMax: 10,
        maxPlayers: 32,
        currentPlayers: ['1', '2', '4', '7'],
        entryFee: 15,
        prizes: ['Trophy', '£100 voucher', 'Free coaching session'],
        organizer: 'Birmingham Badminton Association',
        createdAt: '2024-01-10T10:00:00Z',
    },
    {
        id: 't2',
        name: 'Doubles Championship 2026',
        description: 'Competitive doubles tournament. Find a partner and compete!',
        location: {
            lat: 52.4751,
            lng: -1.8686,
            venue: 'National Indoor Arena',
            address: 'King Edwards Rd, Birmingham B1 2AA',
        },
        date: '2026-04-20T10:00:00Z',
        endDate: '2026-04-21T17:00:00Z',
        format: 'doubles',
        skillLevelMin: 5,
        skillLevelMax: 10,
        maxPlayers: 16,
        currentPlayers: ['2', '4'],
        entryFee: 25,
        prizes: ['Championship Trophy', '£250 cash', 'Pro racket set'],
        organizer: 'Midlands Badminton League',
        createdAt: '2024-01-20T14:00:00Z',
    },
    {
        id: 't3',
        name: 'Beginner Friendly Fun Tournament',
        description: 'No pressure, just fun! Perfect for those new to competitive play.',
        location: {
            lat: 52.4922,
            lng: -1.8745,
            venue: 'Selly Oak Leisure Centre',
            address: 'Bristol Rd, Birmingham B29 6SL',
        },
        date: '2026-02-28T13:00:00Z',
        endDate: '2026-02-28T17:00:00Z',
        format: 'mixed',
        skillLevelMin: 1,
        skillLevelMax: 4,
        maxPlayers: 24,
        currentPlayers: ['3', '5', '8'],
        entryFee: 10,
        prizes: ['Medals', 'Shuttlecock pack'],
        organizer: 'Selly Oak Badminton Club',
        createdAt: '2024-02-01T09:00:00Z',
    },
    {
        id: 't4',
        name: 'University League Finals',
        description: 'The grand finale of the inter-university badminton league.',
        location: {
            lat: 52.4508,
            lng: -1.9305,
            venue: 'University of Birmingham Sport Centre',
            address: 'Edgbaston, Birmingham B15 2TT',
        },
        date: '2026-05-10T11:00:00Z',
        endDate: '2026-05-10T19:00:00Z',
        format: 'singles',
        skillLevelMin: 6,
        skillLevelMax: 10,
        maxPlayers: 16,
        currentPlayers: [],
        entryFee: 0,
        prizes: ['University Trophy', 'Champion Title'],
        organizer: 'BUCS',
        createdAt: '2024-01-25T11:00:00Z',
    },
];

// Mock clubs
export const mockClubs: Club[] = [
    {
        id: 'c1',
        name: 'Birmingham Badminton Club',
        description: 'The largest and oldest badminton club in Birmingham. Weekly sessions, coaching, and social events.',
        avatarUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400',
        location: {
            lat: 52.4862,
            lng: -1.8904,
            address: 'Aston University Sports Centre, Birmingham B4 7ET',
        },
        memberCount: 156,
        members: ['1', '2', '4', '7'],
        activityLevel: 'high',
        meetingDays: ['Tuesday', 'Thursday', 'Saturday'],
        skillLevelRange: [1, 10],
        isOpen: true,
        createdAt: '2020-01-15T10:00:00Z',
    },
    {
        id: 'c2',
        name: 'Aston Shuttlers',
        description: 'Aston University students and alumni. Casual and competitive play welcome!',
        avatarUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400',
        location: {
            lat: 52.4870,
            lng: -1.8895,
            address: 'Aston University, Aston St, Birmingham B4 7ET',
        },
        memberCount: 89,
        members: ['3', '5', '6', '8'],
        activityLevel: 'high',
        meetingDays: ['Monday', 'Wednesday', 'Friday'],
        skillLevelRange: [1, 8],
        isOpen: true,
        createdAt: '2021-09-01T10:00:00Z',
    },
    {
        id: 'c3',
        name: 'Elite Smashers',
        description: 'Competitive club for advanced players. Regular training and tournament preparation.',
        avatarUrl: 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=400',
        location: {
            lat: 52.4668,
            lng: -1.9123,
            address: 'Edgbaston Priory Club, Birmingham B15 3TB',
        },
        memberCount: 34,
        members: ['2', '4'],
        activityLevel: 'high',
        meetingDays: ['Monday', 'Wednesday', 'Saturday', 'Sunday'],
        skillLevelRange: [7, 10],
        isOpen: false,
        createdAt: '2019-06-10T10:00:00Z',
    },
    {
        id: 'c4',
        name: 'Weekend Warriors',
        description: 'Casual weekend club for those who just want to have fun. All levels welcome!',
        avatarUrl: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400',
        location: {
            lat: 52.4589,
            lng: -1.8834,
            address: 'Harborne Leisure Centre, Birmingham B17 9LS',
        },
        memberCount: 67,
        members: ['1', '3', '5', '6', '8'],
        activityLevel: 'medium',
        meetingDays: ['Saturday', 'Sunday'],
        skillLevelRange: [1, 6],
        isOpen: true,
        createdAt: '2022-03-20T10:00:00Z',
    },
];

// Current user for demo
export const mockCurrentUser: Player = {
    id: 'current',
    email: 'demo@badmintonconnect.com',
    name: 'Demo User',
    bio: 'Hackathon demo account! Looking to connect with the badminton community.',
    avatarUrl: 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=400',
    skillLevel: 5,
    playStyle: 'both',
    location: { lat: 52.4862, lng: -1.8904, city: 'Birmingham' },
    stats: {
        wins: 25,
        losses: 20,
        totalMatches: 45,
        winRate: 56,
        preferredDays: ['Wednesday', 'Saturday', 'Sunday'],
        averageRating: 4.4,
    },
    lookingFor: ['casual', 'competitive'],
    createdAt: '2024-02-07T10:00:00Z',
    updatedAt: '2024-02-07T10:00:00Z',
};

// Courts/venues for map
export const mockCourts = [
    {
        id: 'court1',
        name: 'Aston University Sports Centre',
        lat: 52.4862,
        lng: -1.8904,
        courts: 6,
        hourlyRate: 12,
    },
    {
        id: 'court2',
        name: 'National Indoor Arena',
        lat: 52.4751,
        lng: -1.8686,
        courts: 8,
        hourlyRate: 15,
    },
    {
        id: 'court3',
        name: 'Selly Oak Leisure Centre',
        lat: 52.4922,
        lng: -1.8745,
        courts: 4,
        hourlyRate: 10,
    },
    {
        id: 'court4',
        name: 'University of Birmingham Sport Centre',
        lat: 52.4508,
        lng: -1.9305,
        courts: 10,
        hourlyRate: 8,
    },
];
